moviesAPP/src/Entity/HasArtist.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HasArtistRepository")
 */
class HasArtist
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     * @Groups({"movie"})
     */
    private $is_Actor;

    /**
     * @ORM\Column(type="boolean")
     * @Groups({"movie"})
     */
    private $is_Director;

    /**
     * @ORM\ManyToOne(targetEntity="Artist", inversedBy="hasArtist")
     * @ORM\JoinColumn(name="artist_id", referencedColumnName="id")
     * @Groups({"movie"})
     */
    private $artist;

    /**
     * @ORM\ManyToOne(targetEntity="Movie", inversedBy="has_Artist")
     * @ORM\JoinColumn(name="movie_id", referencedColumnName="id")
     */
    private $movie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIsActor(): ?bool
    {
        return $this->is_Actor;
    }

    public function setIsActor(bool $is_Actor): self
    {
        $this->is_Actor = $is_Actor;

        return $this;
    }

    public function getIsDirector(): ?bool
    {
        return $this->is_Director;
    }

    public function setIsDirector(bool $is_Director): self
    {
        $this->is_Director = $is_Director;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(?Artist $artist): self
    {
        $this->artist = $artist;

        return $this;
    }

    public function getMovie(): ?Movie
    {
        return $this->movie;
    }

    public function setMovie(?Movie $movie): self
    {
        $this->movie = $movie;

        return $this;
    }


}

moviesAPP/src/Form/HasArtistType.php
<?php

namespace App\Form;

use App\Entity\Artist;
use App\Entity\HasArtist;
use App\Entity\Movie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
class HasArtistType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('is_Actor')
            ->add('is_Director')
            ->add('artist',EntityType::class, array(
                // looks for choices from this entity
                'class' => Artist::class,
                'choice_label' => 'fullName'
            ))
            ->add('movie',EntityType::class, array(
                'class' => Movie::class,
                'choice_label' => 'name'
                ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => HasArtist::class,
        ]);
    }
}

moviesAPP/src/Controller/HasArtistController.php
<?php

namespace App\Controller;

use App\Entity\HasArtist;
use App\Form\HasArtistType;
use App\Repository\HasArtistRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/api/has-artist")
 */
class HasArtistController extends AbstractController
{
    /**
     * @Route("/", name="has_artist_index", methods="GET")
     */
    public function index(HasArtistRepository $hasArtistRepository): Response
    {
        return $this->render('has_artist/index.html.twig', ['has_artists' => $hasArtistRepository->findAll()]);
    }

    /**
     * @Route("/new", name="has_artist_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $hasArtist = new HasArtist();
        $form = $this->createForm(HasArtistType::class, $hasArtist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($hasArtist);
            $em->flush();

            return $this->redirectToRoute('has_artist_index');
        }

        return $this->render('has_artist/new.html.twig', [
            'has_artist' => $hasArtist,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="has_artist_show", methods="GET")
     */
    public function show(HasArtist $hasArtist): Response
    {
        return $this->render('has_artist/show.html.twig', ['has_artist' => $hasArtist]);
    }

    /**
     * @Route("/{id}/edit", name="has_artist_edit", methods="GET|POST")
     */
    public function edit(Request $request, HasArtist $hasArtist): Response
    {
        $form = $this->createForm(HasArtistType::class, $hasArtist);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('has_artist_index', ['id' => $hasArtist->getId()]);
        }

        return $this->render('has_artist/edit.html.twig', [
            'has_artist' => $hasArtist,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="has_artist_delete", methods="DELETE")
     */
    public function delete(Request $request, HasArtist $hasArtist): Response
    {
        if ($this->isCsrfTokenValid('delete'.$hasArtist->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($hasArtist);
            $em->flush();
        }

        return $this->redirectToRoute('has_artist_index');
    }
}

moviesAPP/templates/has_artist/_delete_form.html.twig
<form method="post" action="{{ path('has_artist_delete', {'id': has_artist.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ has_artist.id) }}">
    <button class="btn">Delete</button>
</form>

moviesAPP/templates/has_artist/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

moviesAPP/templates/has_artist/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit HasArtist{% endblock %}

{% block body %}
    <h1>Edit HasArtist</h1>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {{ include('has_artist/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('has_artist_index') }}">back to list</a>

    {{ include('has_artist/_delete_form.html.twig') }}
{% endblock %}

moviesAPP/templates/has_artist/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}HasArtist index{% endblock %}

{% block body %}
    <h1>HasArtist index</h1>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <table class="table">
        <thead class="table table-sm table-striped table-dark table-bordered table-hover">
            <tr>
                <th>Id</th>
                <th>Is_Actor</th>
                <th>Is_Director</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for has_artist in has_artists %}
            <tr>
                <td>{{ has_artist.id }}</td>
                <td>{{ has_artist.isActor ? 'Yes' : 'No' }}</td>
                <td>{{ has_artist.isDirector ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('has_artist_show', {'id': has_artist.id}) }}">show</a>
                    <a href="{{ path('has_artist_edit', {'id': has_artist.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('has_artist_new') }}">Create new</a>
{% endblock %}

moviesAPP/templates/has_artist/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New HasArtist{% endblock %}

{% block body %}
    <h1>Create new HasArtist</h1>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {{ include('has_artist/_form.html.twig') }}

    <a href="{{ path('has_artist_index') }}">back to list</a>
{% endblock %}

moviesAPP/templates/has_artist/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}HasArtist{% endblock %}

{% block body %}
    <h1>HasArtist</h1>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ has_artist.id }}</td>
            </tr>
            <tr>
                <th>Is_Actor</th>
                <td>{{ has_artist.isActor ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Is_Director</th>
                <td>{{ has_artist.isDirector ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('has_artist_index') }}">back to list</a>

    <a href="{{ path('has_artist_edit', {'id': has_artist.id}) }}">edit</a>

    {{ include('has_artist/_delete_form.html.twig') }}
{% endblock %}